name: update-readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # If you have a large repo and only need a few files, consider 'fetch-depth: 0'
          fetch-depth: 1

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'  # or whichever stable version you want

      - name: Generate README
        run: |
          cd "${{ github.workspace }}/.update"
          go run main.go
        # If your script requires environment variables like GITHUB_USER, add:
        # env:
        #   GITHUB_USER: ${{ secrets.GITHUB_USER }}

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          # The commit command will fail if no changes have been made, so we handle that gracefully:
          git commit -m "auto: Update dynamic content" || echo "No changes to commit."
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
